"""updated pros table

Revision ID: 4ee42b5ef152
Revises: 41dc5e74f833
Create Date: 2025-03-04 13:39:27.927865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ee42b5ef152'
down_revision: Union[str, None] = '41dc5e74f833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pros', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('pros', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('pros', sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('pros', sa.Column('modified_at', sa.DateTime(), nullable=True))
    op.drop_column('pros', 'business_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pros', sa.Column('business_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('pros', 'modified_at')
    op.drop_column('pros', 'location')
    op.drop_column('pros', 'rating')
    op.drop_column('pros', 'bio')
    # ### end Alembic commands ###
