"""Added users, clients, pros tables

Revision ID: 941fc2bd012a
Revises: a545305dcb5f
Create Date: 2025-03-04 13:14:08.774264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '941fc2bd012a'
down_revision: Union[str, None] = 'a545305dcb5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
